// <auto-generated />
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventoryApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731011930_AddWarehouseNavigation")]
    partial class AddWarehouseNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriticalLevel")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("integer");

                    b.Property<int>("VariantId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariantId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriticalLevel = 5,
                            CurrentStock = 25,
                            VariantId = 1,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CriticalLevel = 10,
                            CurrentStock = 4,
                            VariantId = 2,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 3,
                            CriticalLevel = 10,
                            CurrentStock = 50,
                            VariantId = 3,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 4,
                            CriticalLevel = 5,
                            CurrentStock = 12,
                            VariantId = 4,
                            WarehouseId = 1
                        },
                        new
                        {
                            Id = 5,
                            CriticalLevel = 5,
                            CurrentStock = 8,
                            VariantId = 5,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 6,
                            CriticalLevel = 3,
                            CurrentStock = 15,
                            VariantId = 9,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 7,
                            CriticalLevel = 5,
                            CurrentStock = 2,
                            VariantId = 10,
                            WarehouseId = 2
                        },
                        new
                        {
                            Id = 8,
                            CriticalLevel = 4,
                            CurrentStock = 20,
                            VariantId = 12,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 9,
                            CriticalLevel = 10,
                            CurrentStock = 30,
                            VariantId = 15,
                            WarehouseId = 3
                        },
                        new
                        {
                            Id = 10,
                            CriticalLevel = 5,
                            CurrentStock = 7,
                            VariantId = 19,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 11,
                            CriticalLevel = 2,
                            CurrentStock = 3,
                            VariantId = 23,
                            WarehouseId = 4
                        },
                        new
                        {
                            Id = 12,
                            CriticalLevel = 5,
                            CurrentStock = 18,
                            VariantId = 27,
                            WarehouseId = 5
                        },
                        new
                        {
                            Id = 13,
                            CriticalLevel = 4,
                            CurrentStock = 9,
                            VariantId = 30,
                            WarehouseId = 5
                        });
                });

            modelBuilder.Entity("InventoryApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pamuklu Günlük Tişört",
                            Name = "Oversize Tişört",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hafif Spor Ayakkabı",
                            Name = "Koşu Ayakkabısı",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Esnek Denim Pantolon",
                            Name = "Slim Fit Kot Pantolon",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kışlık Polar Sweatshirt",
                            Name = "Kapşonlu Sweatshirt",
                            Price = 549.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Hakiki Deri Mont",
                            Name = "Deri Ceket",
                            Price = 2499.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Çok Cepli Rahat Pantolon",
                            Name = "Kargo Pantolon",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Günlük Kullanım Çantası",
                            Name = "Canvas Sırt Çantası",
                            Price = 449.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "İşlemeli Pamuklu Şapka",
                            Name = "Beyzbol Şapkası",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Nefes Alabilir Kumaş",
                            Name = "Sporcu Atleti",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Su Geçirmez Rüzgarlık",
                            Name = "Yağmurluk",
                            Price = 899.99m
                        });
                });

            modelBuilder.Entity("InventoryApp.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Siyah",
                            ProductId = 1,
                            SKU = "TIS-SIY-S",
                            Size = "S"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Siyah",
                            ProductId = 1,
                            SKU = "TIS-SIY-M",
                            Size = "M"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Siyah",
                            ProductId = 1,
                            SKU = "TIS-SIY-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Beyaz",
                            ProductId = 1,
                            SKU = "TIS-BEY-S",
                            Size = "S"
                        },
                        new
                        {
                            Id = 5,
                            Color = "Beyaz",
                            ProductId = 1,
                            SKU = "TIS-BEY-M",
                            Size = "M"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Beyaz",
                            ProductId = 1,
                            SKU = "TIS-BEY-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Gri",
                            ProductId = 1,
                            SKU = "TIS-GRI-M",
                            Size = "M"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Gri",
                            ProductId = 1,
                            SKU = "TIS-GRI-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Mavi",
                            ProductId = 2,
                            SKU = "AYA-MAV-40",
                            Size = "40"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Mavi",
                            ProductId = 2,
                            SKU = "AYA-MAV-42",
                            Size = "42"
                        },
                        new
                        {
                            Id = 11,
                            Color = "Mavi",
                            ProductId = 2,
                            SKU = "AYA-MAV-44",
                            Size = "44"
                        },
                        new
                        {
                            Id = 12,
                            Color = "Siyah",
                            ProductId = 2,
                            SKU = "AYA-SIY-41",
                            Size = "41"
                        },
                        new
                        {
                            Id = 13,
                            Color = "Siyah",
                            ProductId = 2,
                            SKU = "AYA-SIY-42",
                            Size = "42"
                        },
                        new
                        {
                            Id = 14,
                            Color = "Siyah",
                            ProductId = 2,
                            SKU = "AYA-SIY-43",
                            Size = "43"
                        },
                        new
                        {
                            Id = 15,
                            Color = "Mavi",
                            ProductId = 3,
                            SKU = "PAN-MAV-30",
                            Size = "30/32"
                        },
                        new
                        {
                            Id = 16,
                            Color = "Mavi",
                            ProductId = 3,
                            SKU = "PAN-MAV-32",
                            Size = "32/32"
                        },
                        new
                        {
                            Id = 17,
                            Color = "Siyah",
                            ProductId = 3,
                            SKU = "PAN-SIY-32",
                            Size = "32/32"
                        },
                        new
                        {
                            Id = 18,
                            Color = "Siyah",
                            ProductId = 3,
                            SKU = "PAN-SIY-34",
                            Size = "34/32"
                        },
                        new
                        {
                            Id = 19,
                            Color = "Kırmızı",
                            ProductId = 4,
                            SKU = "SWE-KIR-M",
                            Size = "M"
                        },
                        new
                        {
                            Id = 20,
                            Color = "Kırmızı",
                            ProductId = 4,
                            SKU = "SWE-KIR-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 21,
                            Color = "Lacivert",
                            ProductId = 4,
                            SKU = "SWE-LAC-M",
                            Size = "M"
                        },
                        new
                        {
                            Id = 22,
                            Color = "Lacivert",
                            ProductId = 4,
                            SKU = "SWE-LAC-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 23,
                            Color = "Siyah",
                            ProductId = 5,
                            SKU = "CEK-SIY-L",
                            Size = "L"
                        },
                        new
                        {
                            Id = 24,
                            Color = "Kahverengi",
                            ProductId = 5,
                            SKU = "CEK-KAH-XL",
                            Size = "XL"
                        },
                        new
                        {
                            Id = 25,
                            Color = "Haki",
                            ProductId = 6,
                            SKU = "KAR-HAK-32",
                            Size = "32"
                        },
                        new
                        {
                            Id = 26,
                            Color = "Haki",
                            ProductId = 6,
                            SKU = "KAR-HAK-34",
                            Size = "34"
                        },
                        new
                        {
                            Id = 27,
                            Color = "Bej",
                            ProductId = 7,
                            SKU = "CAN-BEJ-STD",
                            Size = "Standart"
                        },
                        new
                        {
                            Id = 28,
                            Color = "Siyah",
                            ProductId = 7,
                            SKU = "CAN-SIY-STD",
                            Size = "Standart"
                        },
                        new
                        {
                            Id = 29,
                            Color = "Siyah",
                            ProductId = 8,
                            SKU = "SAP-SIY-AYR",
                            Size = "Ayarlanabilir"
                        },
                        new
                        {
                            Id = 30,
                            Color = "Sarı",
                            ProductId = 10,
                            SKU = "YAG-SAR-L",
                            Size = "L"
                        });
                });

            modelBuilder.Entity("InventoryApp.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "İstanbul",
                            Name = "İstanbul Merkez Depo"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Trabzon",
                            Name = "Trabzon Şube Depo"
                        },
                        new
                        {
                            Id = 3,
                            Location = "İzmir",
                            Name = "İzmir Lojistik Merkezi"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Ankara",
                            Name = "Ankara Bölge Deposu"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Antalya",
                            Name = "Antalya Dağıtım Deposu"
                        });
                });

            modelBuilder.Entity("InventoryApp.Models.Inventory", b =>
                {
                    b.HasOne("InventoryApp.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryApp.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });
#pragma warning restore 612, 618
        }
    }
}
